modLoader = "javafml"
loaderVersion = "[47,)"
license = "https://github.com/Sm0keySa1m0n/Railcraft/blob/1.20.x/LICENSE.md"
issueTrackerURL = "https://github.com/Sm0keySa1m0n/Railcraft/issues"

[[mods]]
  modId = "railcraft"
  version = "${mod_version}"
  displayName = "Railcraft"
  logoFile = "pack.png"
  credits = "Created by CovertJaguar and other contributions at Github"
  authors = "CovertJaguar, Sm0keySa1m0n, 3divad99"
  description = "Redefine your rails"

[[dependencies.railcraft]]
  mandatory = true
  modId = "forge"
  ordering = "AFTER"
  side = "BOTH"
  versionRange = "[47,)"
[[dependencies.railcraft]]
  mandatory = true
  modId = "minecraft"
  ordering = "NONE"
  side = "BOTH"
  versionRange = "[1.20.1,1.21)"
