modLoader="javafml"
loaderVersion = "[42,)"
license = "https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/LICENSE.md"
issueTrackerURL = "https://github.com/Railcraft/Railcraft/Issues"

[[mods]]
  modId = "railcraft"
  version = "${file.jarVersion}"
  displayName = "Railcraft"
  displayURL = "https://railcraft.info"
  logoFile = "pack.png"
  credits = "Created by CovertJaguar and other contributions at Github"
  authors = "CovertJaguar, Sm0keySa1m0n"
  description = '''
  Redefine your rails
  '''

[[dependencies.railcraft]]
  mandatory = true
  modId = "forge"
  ordering = "NONE"
  side = "BOTH"
  versionRange = "[42,)"
