modLoader = "javafml"
loaderVersion = "[1,)"
license = "https://github.com/railcraft-reborn/railcraft/blob/1.20.x/LICENSE.md"
issueTrackerURL = "https://github.com/railcraft-reborn/railcraft/issues"

[[mods]]
  modId = "railcraft"
  version = "${mod_version}"
  displayName = "Railcraft Reborn"
  updateJSONURL = "https://api.modrinth.com/updates/railcraft-reborn/forge_updates.json"
  logoFile = "pack.png"
  credits = "Created by CovertJaguar and other contributions at GitHub"
  modUrl = "https://www.curseforge.com/minecraft/mc-mods/railcraft-reborn"
  authors = "Sm0keySa1m0n, Edivad99"
  description = "Redefine your rails"

[[dependencies.railcraft]]
  mandatory = true
  modId = "neoforge"
  ordering = "AFTER"
  side = "BOTH"
  versionRange = "[20.2,)"
[[dependencies.railcraft]]
  mandatory = true
  modId = "minecraft"
  ordering = "NONE"
  side = "BOTH"
  versionRange = "[1.20.2,1.21)"
