name: Deploy Nightly
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    name: Deploy nightly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 1.19.x

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Restore gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Compile
        env:
          GITHUB_NIGHTLY: true
        run: |
          ./gradlew hideOfficialWarningUntilChanged
          ./gradlew build --no-daemon --max-workers 1

      - name: Test
        run: |
          ./gradlew hideOfficialWarningUntilChanged
          ./gradlew runGameTestServer --no-daemon --max-workers 1

      - name: Zip Files
        run : |
          powershell "Compress-Archive ./build/libs ./railcraft-nightly.zip"

      - name: Deploy Windows nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/Sm0keySa1m0n/Railcraft/releases/50391151/assets{?name,label}
          release_id: 50391151
          asset_path: ./railcraft-nightly.zip
          asset_name: railcraft-nightly-1.19.x-$$.zip
          asset_content_type: application/zip
          max_releases: 5
