name: Deploy Nightly
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    name: Deploy nightly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: mc-1.16.5
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ./.gradle/caches
            ./.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Compile
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
          GITHUB_NIGHTLY: true
        run: |
          ./gradlew hideOfficialWarningUntilChanged
          ./gradlew build
      - name: Zip Files
        run : |
          powershell "Compress-Archive ./build/libs ./railcraft-nightly.zip"
      - name: Deploy Windows nightly
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/Sm0keySa1m0n/Railcraft/releases/50391151/assets{?name,label}
          release_id: 50391151
          asset_path: ./railcraft-nightly.zip
          asset_name: railcraft-nightly-1.16.5-$$.zip
          asset_content_type: application/zip
          max_releases: 5
